In [1]:
%matplotlib inline

import torch
import numpy as np

In [2]:
data = [
    [1,2],
    [3,4],
]

x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data) # x_dataの特性（プロパティ）を維持
print('Ones Tensor: \n', x_ones, '\n')

x_rand = torch.rand_like(x_data, dtype=torch.float) #x_dataのdatatypeを上書き保存
print('Random Tensor: \n', x_rand, '\n')

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7819, 0.0359],
        [0.9279, 0.2279]]) 



In [5]:
# shapeからtensorのサイズを決める
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print('Random Tensor: \n', rand_tensor, '\n')
print('Ones Tensor: \n', ones_tensor, '\n')
print('Zeros Tensor: \n', zeros_tensor, '\n')

Random Tensor: 
 tensor([[0.0185, 0.0601, 0.1280],
        [0.2232, 0.5911, 0.5545]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [6]:
tensor = torch.rand(3,4)

print('Shape of tensor: ', tensor.shape)
print('Datatype of tensor: ', tensor.dtype)
print('Device tensor is stored on: ', tensor.device)

Shape of tensor:  torch.Size([3, 4])
Datatype of tensor:  torch.float32
Device tensor is stored on:  cpu


In [7]:
# GPUが使用可能であれば，GPU上にテンソルを移動させる
if torch.cuda.is_available():
    tensor = tensor.to('cuda:0')

In [8]:
# numpy-likeなtensorの操作
tensor = torch.ones(4,4)
print('First row: ', tensor[0])
print('First column: ', tensor[:,0])
print('Last column: ', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
# tensorの結合
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [10]:
# 2つのテンソルの掛け算，y1, y2, y3は全て同じ結果になる
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [11]:
# 2つのテンソルの要素ごとの積，z1, z2, z3は同じ値になる
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [13]:
# 1要素のテンソルを扱う場合には，.item()を使用することでPythonの数値型変数に変換可能
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [14]:
# インプレース操作，演算結果をオペランドに格納する．
print(tensor, '\n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [17]:
# numpyへの変換
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [18]:
# この際，テンソルが変化すると，numpy側も変化する．（参照渡し）
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
# numpy array to tensor
n = np.ones(5)
t = torch.from_numpy(n)

In [20]:
#この際，numpyが変化するとテンソルも変化する（参照渡し）
n += 1
print(t)
print(n)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
