In [1]:
%matplotlib inline

import torch
import numpy as np

In [3]:
data = [
    [1,2],
    [3,4],
]

x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones = torch.ones_like(x_data) # x_dataの特性（プロパティ）を維持
print('Ones Tensor: \n', x_ones, '\n')

x_rand = torch.rand_like(x_data, dtype=torch.float) #x_dataのdatatypeを上書き保存
print('Random Tensor: \n', x_rand, '\n')

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8607, 0.8665],
        [0.0110, 0.6423]]) 



In [6]:
# shapeからtensorのサイズを決める
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print('Random Tensor: \n', rand_tensor, '\n')
print('Ones Tensor: \n', ones_tensor, '\n')
print('Zeros Tensor: \n', zeros_tensor, '\n')

Random Tensor: 
 tensor([[0.9408, 0.4840, 0.1150],
        [0.6325, 0.1454, 0.2061]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [7]:
tensor = torch.rand(3,4)

print('Shape of tensor: ', tensor.shape)
print('Datatype of tensor: ', tensor.dtype)
print('Device tensor is stored on: ', tensor.device)

Shape of tensor:  torch.Size([3, 4])
Datatype of tensor:  torch.float32
Device tensor is stored on:  cpu


In [9]:
# GPUが使用可能であれば，GPU上にテンソルを移動させる
if torch.cuda.is_available():
    tensor = tensor.to('cuda:0')

In [ ]:
tensor = torch.ones(4,4)
print()